version: '3.8'

services:
  nginx:
    tty: true
    restart: always
    container_name: nginx
    hostname: nginx
    image: danxiaonuo/nginx:latest
    volumes:
      - ./conf/nginx/www:/www:rw,cached
      - ./conf/nginx/ssl:/ssl:rw,cached
      - ./conf/nginx/vhost:/data/nginx/conf/vhost:rw,cached
      - ./conf/nginx/nginx.conf:/data/nginx/conf/nginx.conf:rw,cached
      - ./conf/nginx/gzip.conf:/data/nginx/conf/gzip.conf:rw,cached
      - ./conf/nginx/cache.conf:/data/nginx/conf/cache.conf:rw,cached
      - ./conf/nginx/proxy.conf:/data/nginx/conf/proxy.conf:rw,cached
      - ./conf/nginx/waf.conf:/data/nginx/conf/waf.conf:rw,cached
      - ./conf/nginx/waf:/data/nginx/conf/waf:rw,cached
      - ./logs/nginx:/data/nginx/logs:delegated
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
    cap_add:
     - ALL
    sysctls:
     - net.ipv4.tcp_ecn=1
     - net.ipv4.tcp_ecn_fallback=1
     - net.ipv4.tcp_congestion_control=bbrplus
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535
    ports:
    - "80:80"
    - "443:443"
    dns:
    - 114.114.114.114
    - 119.29.29.29
